import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

function getClients(req: NextRequest) { const url = process.env.NEXT_PUBLIC_SUPABASE_URL!; const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!; const service = process.env.SUPABASE_SERVICE_ROLE_KEY!; const token = req.headers.get("authorization")?.replace("Bearer ", ""); const userClient = createClient(url, anon, { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false, autoRefreshToken: false } }); const adminClient = createClient(url, service, { auth: { persistSession: false, autoRefreshToken: false } }); return { userClient, adminClient }; }
async function isMaster(adminClient: ReturnType<typeof getClients>["adminClient"], userClient: ReturnType<typeof getClients>["userClient"]) { const { data: { user } } = await userClient.auth.getUser(); if (!user) return false; const { data: p } = await adminClient.from("profiles").select("role,approval_status").eq("id", user.id).maybeSingle(); return p?.role === "master" && p?.approval_status === "approved"; }

export async function DELETE(req: NextRequest, context: { params: Promise<{ classroomId: string; userId: string }> }) { const { userClient, adminClient } = getClients(req); if (!(await isMaster(adminClient, userClient))) return NextResponse.json({ error: "Master access required." }, { status: 403 }); const { classroomId, userId } = await context.params; const { error } = await adminClient.from("classroom_members").delete().eq("classroom_id", classroomId).eq("user_id", userId); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ ok: true }); }

export async function PATCH(req: NextRequest, context: { params: Promise<{ classroomId: string; userId: string }> }) { const { userClient, adminClient } = getClients(req); if (!(await isMaster(adminClient, userClient))) return NextResponse.json({ error: "Master access required." }, { status: 403 }); const { classroomId, userId } = await context.params; const body = await req.json().catch(() => null); const toId = String(body?.to_classroom_id || ""); if (!toId) return NextResponse.json({ error: "Destination classroom required." }, { status: 400 }); await adminClient.from("classroom_members").delete().eq("classroom_id", classroomId).eq("user_id", userId); const { error } = await adminClient.from("classroom_members").insert({ classroom_id: toId, user_id: userId, joined_via: "master_moved" }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ ok: true }); }
