import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

type Ctx = { params: Promise<{ classroomId: string }> };
const isValidEmail = (value: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
async function auth(req: NextRequest) { const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,srv=process.env.SUPABASE_SERVICE_ROLE_KEY; if(!url||!key||!srv) throw new Error('Missing Supabase environment variables.'); const token=req.headers.get('authorization')?.replace('Bearer ',''); if(!token) return {error:NextResponse.json({error:'Missing authorization token.'},{status:401})} as const; const userClient=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}}); const adminClient=createClient(url,srv,{auth:{persistSession:false,autoRefreshToken:false}}); const {data:{user}}=await userClient.auth.getUser(); if(!user) return {error:NextResponse.json({error:'Unauthorized.'},{status:401})} as const; const {data:profile}=await adminClient.from('profiles').select('role,approval_status').eq('id',user.id).maybeSingle(); if(!profile||profile.role!=='master'||profile.approval_status!=='approved') return {error:NextResponse.json({error:'Master access required.'},{status:403})} as const; return {adminClient}; }

export async function POST(req: NextRequest, ctx: Ctx) { const a=await auth(req); if('error' in a) return a.error; const {classroomId}=await ctx.params; const body=await req.json(); const ids = [...new Set(((body?.studentUserIds ?? []) as string[]).filter((id) => Boolean(id)))]; if(!ids.length) return NextResponse.json({error:'Please select at least one student.'},{status:400}); const {data:existing}=await a.adminClient.from('classroom_members').select('user_id').eq('classroom_id',classroomId).in('user_id',ids); const set=new Set((existing??[]).map((r: { user_id: string }) => r.user_id)); const toAdd = ids.filter((id) => !set.has(id)); if(toAdd.length){ const {error}=await a.adminClient.from('classroom_members').insert(toAdd.map((id) => ({ classroom_id: classroomId, user_id: id, joined_via: 'master_added' }))); if(error) return NextResponse.json({error:error.message},{status:500}); } return NextResponse.json({added_count:toAdd.length,already_enrolled_count:ids.length-toAdd.length}); }

export async function PUT(req: NextRequest, ctx: Ctx) { const a=await auth(req); if('error' in a) return a.error; const {classroomId}=await ctx.params; const body=await req.json().catch(()=>null); const fullName=String(body?.full_name||'').trim(); const email=String(body?.email||'').trim().toLowerCase(); if(!fullName) return NextResponse.json({error:'Student full name is required.'},{status:400}); if(!isValidEmail(email)) return NextResponse.json({error:'A valid student email is required.'},{status:400});
const {data:existing}=await a.adminClient.from('profiles').select('id,full_name,email,role').ilike('email',email).maybeSingle(); let userId=existing?.id; let status='created_and_added'; if(existing){ if(existing.role&&existing.role!=='student') return NextResponse.json({error:'That email belongs to a non-student account.'},{status:400}); status='existing_user_added'; }
if(!userId){ const {data:inv,error:invErr}=await a.adminClient.auth.admin.inviteUserByEmail(email,{data:{full_name:fullName,role:'student',requested_role:'student',approval_status:'approved'},redirectTo:`${req.nextUrl.origin}/login`}); if(invErr||!inv?.user?.id) return NextResponse.json({error:invErr?.message||'Failed to invite student.'},{status:500}); userId=inv.user.id; }
await a.adminClient.from('profiles').upsert({id:userId,full_name:existing?.full_name||fullName,email,role:'student',requested_role:'student',approval_status:'approved'},{onConflict:'id'});
const {data:membership}=await a.adminClient.from('classroom_members').select('id').eq('classroom_id',classroomId).eq('user_id',userId).maybeSingle(); if(!membership){ const {error}=await a.adminClient.from('classroom_members').insert({classroom_id:classroomId,user_id:userId,joined_via:'master_created'}); if(error) return NextResponse.json({error:error.message},{status:500}); } else { status='already_enrolled'; }
return NextResponse.json({user_id:userId,full_name:existing?.full_name||fullName,email,status}); }
